//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairStudio
{


    public partial class stuffManagement
    {

        /// <summary>
        /// FileUpload2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload FileUpload2;

        /// <summary>
        /// TextBox11 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox11;

        /// <summary>
        /// Button20 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button20;

        /// <summary>
        /// TextBox12 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox12;

        /// <summary>
        /// TextBox13 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox13;

        /// <summary>
        /// TextBox14 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox14;

        /// <summary>
        /// TextBox15 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox15;

        /// <summary>
        /// TextBox16 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TextBox16;

        /// <summary>
        /// Button12 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button12;

        /// <summary>
        /// Button13 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button13;

        /// <summary>
        /// Button14 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button14;

        /// <summary>
        /// SqlDataSource11 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource11;

        /// <summary>
        /// GridView11 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridView11;

        // Aliases used by code-behind (mapped to TextBox11-16 in ASPX)
        protected global::System.Web.UI.WebControls.TextBox TextBox1 { get { return TextBox11; } }
        protected global::System.Web.UI.WebControls.TextBox TextBox2 { get { return TextBox12; } }
        protected global::System.Web.UI.WebControls.TextBox TextBox3 { get { return TextBox13; } }
        protected global::System.Web.UI.WebControls.TextBox TextBox4 { get { return TextBox14; } }
        protected global::System.Web.UI.WebControls.TextBox TextBox5 { get { return TextBox15; } }
        protected global::System.Web.UI.WebControls.TextBox TextBox6 { get { return TextBox16; } }
        protected global::System.Web.UI.WebControls.FileUpload FileUpload1 { get { return FileUpload2; } }
        protected global::System.Web.UI.WebControls.GridView GridView1 { get { return GridView11; } }
    }
}
